version: "3"

services:
  web:
    build: ./image
    image: tt-rss_docker
    container_name: rss_web
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:9.6-alpine
    container_name: rss_db
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
