version: '3'
services:
    web:
        build: image
        image: tt-rss_docker
        container_name: rss_web
        volumes:
            - ./tt-rss:/srv/www/tt-rss
        networks:
            - network
        ports:
            - '127.0.0.1:80:80'
        depends_on:
            - db
    db:
        image: postgres:9.5-alpine
        container_name: rss_db
        volumes:
            - data:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - network
        environment:
            - POSTGRES_PASSWORD=postgres

volumes:
    data:

networks:
    network:
