version: "3"

services:
  web:
    build: ./image
    image: tt-rss_docker
    container_name: rss_web
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - web_data:/srv/www/tt-rss
    depends_on:
      - db
  db:
    image: postgres:9.6-alpine
    container_name: rss_db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  web_data:
  db_data:
