version: '3'
services:
    web:
        build: .
        image: tt-rss_docker
        container_name: rss_web
        volumes:
            - ./tt-rss:/srv/www/tt-rss
        networks:
            - network
        ports:
            - "80:80"
            - "9001:9001"
        depends_on:
            - db
    db:
        image: postgres:9.5-alpine
        container_name: rss_db
        volumes:
            - data:/var/lib/postgresql/data
            - ./backups:/backups
        networks:
            - network
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes:
    data:

networks:
    network:
